### PR TITLE
Using JS & Regex - fixed the issue

### LINKED ISSUE #25: Extending issue 13 - Adjust the font size of p element starting with "Updated" as per the original blog site
Adjust the font size of p element starting with "Updated" as per the original blog site

image

### PR DESCRIPTION
**Pull request by meejain**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #25 

Test URLs:
- Before: https://main--impala--mkclawson.hlx.live/blog/garaged
- After: https://issue-13-testingupdated--impala--mkclawson.hlx.live/blog/garaged

### CODE REVIEW

File: scripts/scripts.js [hunk 1]
```diff
@@ -166,3 +160,5 @@ async function loadPage() {
 }
 
 loadPage();
+
+document.querySelectorAll('.blog main > .section > .default-content-wrapper p').forEach((x) => { if (/^Updated/.test(x.textContent)) x.style.fontSize = '14px'; });
```
Comment (helms-charity) [inline scripts/scripts.js:164]: Can we change this  so that it just adds a class "updated" to the FIRST instance of that, instead of "for each"? We will keep the font stying in the CSS.

Comment (meejain) [reply scripts/scripts.js]: Sure. Please check now.

Comment (helms-charity) [reply scripts/scripts.js]: Thanks! I think this allows the author to have some control, and also future styling for breakpoints can easily be done.
